title: Cobbler
description: Officaial website for the Cobbler-Project.
url: "https://cobbler.github.io"
lsi: false
highlighter: rouge
markdown: kramdown
permalink: "/blog/:year/:month/:day/:title.html"
paginate: 5
paginate_path: "/blog/:num/"
exclude: ['README.md', 'Dockerfile', 'Gemfile', 'Gemfile.lock', 'dockerfiles', '_site', '.idea']
plugins:
  - jekyll-coffeescript
  - jekyll-gist
  - jekyll-github-metadata
  - jekyll-paginate
  - jekyll-relative-links
  - jekyll-optional-front-matter
  - jekyll-readme-index
  - jekyll-default-layout
  - jekyll-titles-from-headings
cobbler:
  version: 3.0.1
  released: 2019-09-08
  versions: [3.0.1]
